### ISSUE TITLE
What's the input supposed to be of UTF32-BE?

### ISSUE THREAD

**Issue by BeyondMagic** [andrewathalye/unicode-rust#1]
Is there any examples?

The following doesn't work;

`00003072`, `0b00003072`, `00 00 30 72`, `00 00 30 72`, `U00003072`

Tested with both `-s` and `-b`
```
$: ./unicode -f -s <<< "00002524" > new
thread 'main' panicked at 'Invalid UTF-32 input.', src/main.rs:255:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It works though on many converters:

![image](https://user-images.githubusercontent.com/51831435/141875063-e2daa995-490f-4fd0-a198-c8286d11ba7f.png)

**Comment by andrewathalye** [comment]
It's actually intended to take binary UTF-32 input. You can produce it using `echo -ne '\x00\x00\x25\x24'` for example.
The arguments here would be `./unicode -f -b` to convert it to UTF-8.
For your second example:
`echo -ne '\x00\x00\x30\x72\x00\x00\x30\x6f' | ./unicode -f -b` returns `ひは`
If you still encounter issues after trying this, please let me know though.

**Comment by BeyondMagic** [comment]
I see, it works with the binary instead. Thanks for the fast response.

**Comment by andrewathalye** [comment]
Also you might want to consider using iconv for this purpose in general, if available. It has better support for different encodings and is likely more standards-compliant. This converter, for example, will likely accept UTF-8 that is not efficiently encoded, in violation of the specification.
